name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liVNN8gwWnZ79VHj"
GITHUB_OWNER = "ywt"
GITHUB_REPO = "NavSiteTao"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsite-axv.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsite-axv.pages.dev"

